apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-apps-project-applicationset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: app-projects
                namespace: argocd
              selector:
                matchExpressions:
                  - key: in_cluster
                    operator: In
                    values: ['true']
          - clusters: {}
  template:
    metadata:
      name: '{{.name}}-app-project'
    spec:
      project: 'shared'
      sources:
        - repoURL: >-
            {{.metadata.annotations.addons_repo_url}}
          path: 'charts/{{.values.addonChart}}'
          targetRevision: HEAD
          helm:
            valueFiles:
              - $values/team-appsets/teams.yaml
        - repoURL: >-
            https://gitlab.com/cloud8870409/argo-cluster-secrets.git
          targetRevision: HEAD
          ref: values
      destination:
        name: '{{.name}}'
        namespace: 'argocd'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
          - ApplyOutofSyncOnly=true